version: '3.6'

services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
      - 8989:3000
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - 27017:27017
    
